bcache: hack sysfs macro code to avoid conflict with mm cache_show
Otherwise the build fails as follows:

In file included from drivers/md/bcache/super.c:132:
drivers/md/bcache/sysfs.c:719: error: conflicting types for ‘cache_show’
include/linux/slab.h:224: note: previous declaration of ‘cache_show’ was here